name: "pre-release"
on:
  push:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/checkout@v2
      - run: make

      - name: upload
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            out/Kino.pub.zip